spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# App Properties
token:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000 # 24 hours valid
